"""Unified error-code catalogue (P6).

Every MCP handler should reference the symbolic constants defined here when
constructing ``err(...)`` responses so that callers can reliably branch on
``error_code`` without doing string comparisons against ad-hoc literals.
"""

from __future__ import annotations

# Environment / protocol -----------------------------------------------------
ARCH_MISMATCH = "ARCH_MISMATCH"
PROTOCOL_SHAPE_MISMATCH = "PROTOCOL_SHAPE_MISMATCH"
UNAVAILABLE_OUTSIDE_EDITOR = "UNAVAILABLE_OUTSIDE_EDITOR"
UNKNOWN_COMMAND = "UNKNOWN_COMMAND"
UNKNOWN_ERROR = "UNKNOWN_ERROR"
MISSING_PARAMETERS = "MISSING_PARAMETERS"
INVALID_PARAMETERS = "INVALID_PARAMETERS"

# Job lifecycle --------------------------------------------------------------
JOB_NOT_FOUND = "JOB_NOT_FOUND"
JOB_TIMEOUT = "JOB_TIMEOUT"
JOB_CANCELLED = "JOB_CANCELLED"

# Blueprint / graph editing --------------------------------------------------
NODE_NOT_FOUND = "NODE_NOT_FOUND"
PIN_INCOMPATIBLE = "PIN_INCOMPATIBLE"
GRAPH_NOT_SUPPORTED = "GRAPH_NOT_SUPPORTED"
GRAPH_NOT_FOUND = "GRAPH_NOT_FOUND"
COMPILE_FAILED = "COMPILE_FAILED"

# Write operations -----------------------------------------------------------
ASSET_VALIDATION_FAILED = "ASSET_VALIDATION_FAILED"
ASSET_NOT_FOUND = "ASSET_NOT_FOUND"
SAVE_FAILED = "SAVE_FAILED"
ROLLBACK_FAILED = "ROLLBACK_FAILED"

# Input system ---------------------------------------------------------------
LEGACY_INPUT_PATH = "LEGACY_INPUT_PATH"

# Safety ---------------------------------------------------------------------
UNSAFE_COMMAND_REQUIRED = "UNSAFE_COMMAND_REQUIRED"

# BlendSpace / animation -----------------------------------------------------
BLEND_SPACE_READ_FAILED = "BLEND_SPACE_READ_FAILED"
BLEND_SPACE_WRITE_FAILED = "BLEND_SPACE_WRITE_FAILED"
ANIM_BP_READ_FAILED = "ANIM_BP_READ_FAILED"
ANIM_BP_WRITE_FAILED = "ANIM_BP_WRITE_FAILED"
ANIM_BP_STATE_NOT_FOUND = "ANIM_BP_STATE_NOT_FOUND"
ANIM_BP_STATE_MACHINE_NOT_FOUND = "ANIM_BP_STATE_MACHINE_NOT_FOUND"

# Domain-specific codes surfaced by current handlers -------------------------
INVALID_AXIS = "INVALID_AXIS"
INVALID_SAMPLES = "INVALID_SAMPLES"
INVALID_BINDING = "INVALID_BINDING"
INVALID_VALUE_TYPE = "INVALID_VALUE_TYPE"
INVALID_RESTORE_POLICY = "INVALID_RESTORE_POLICY"
INVALID_SNAPSHOT = "INVALID_SNAPSHOT"
SESSION_CAPTURE_FAILED = "SESSION_CAPTURE_FAILED"
SESSION_SAVE_FAILED = "SESSION_SAVE_FAILED"
SESSION_LOAD_FAILED = "SESSION_LOAD_FAILED"
SESSION_MISSING = "SESSION_MISSING"
OPEN_ASSET_FAILED = "OPEN_ASSET_FAILED"
FOCUS_ASSET_FAILED = "FOCUS_ASSET_FAILED"
FOCUS_GRAPH_FAILED = "FOCUS_GRAPH_FAILED"
FOCUS_NODE_FAILED = "FOCUS_NODE_FAILED"
SELECT_ACTOR_FAILED = "SELECT_ACTOR_FAILED"
CREATE_INPUT_ACTION_FAILED = "CREATE_INPUT_ACTION_FAILED"
CREATE_INPUT_CONTEXT_FAILED = "CREATE_INPUT_CONTEXT_FAILED"
INPUT_MAPPING_FAILED = "INPUT_MAPPING_FAILED"
LIST_INPUT_MAPPINGS_FAILED = "LIST_INPUT_MAPPINGS_FAILED"

ALL_ERROR_CODES = (
    ARCH_MISMATCH,
    PROTOCOL_SHAPE_MISMATCH,
    UNAVAILABLE_OUTSIDE_EDITOR,
    UNKNOWN_COMMAND,
    UNKNOWN_ERROR,
    MISSING_PARAMETERS,
    INVALID_PARAMETERS,
    JOB_NOT_FOUND,
    JOB_TIMEOUT,
    JOB_CANCELLED,
    NODE_NOT_FOUND,
    PIN_INCOMPATIBLE,
    GRAPH_NOT_SUPPORTED,
    GRAPH_NOT_FOUND,
    COMPILE_FAILED,
    ASSET_VALIDATION_FAILED,
    ASSET_NOT_FOUND,
    SAVE_FAILED,
    ROLLBACK_FAILED,
    LEGACY_INPUT_PATH,
    UNSAFE_COMMAND_REQUIRED,
    BLEND_SPACE_READ_FAILED,
    BLEND_SPACE_WRITE_FAILED,
    ANIM_BP_READ_FAILED,
    ANIM_BP_WRITE_FAILED,
    ANIM_BP_STATE_NOT_FOUND,
    ANIM_BP_STATE_MACHINE_NOT_FOUND,
    INVALID_AXIS,
    INVALID_SAMPLES,
    INVALID_BINDING,
    INVALID_VALUE_TYPE,
    INVALID_RESTORE_POLICY,
    INVALID_SNAPSHOT,
    SESSION_CAPTURE_FAILED,
    SESSION_SAVE_FAILED,
    SESSION_LOAD_FAILED,
    SESSION_MISSING,
    OPEN_ASSET_FAILED,
    FOCUS_ASSET_FAILED,
    FOCUS_GRAPH_FAILED,
    FOCUS_NODE_FAILED,
    SELECT_ACTOR_FAILED,
    CREATE_INPUT_ACTION_FAILED,
    CREATE_INPUT_CONTEXT_FAILED,
    INPUT_MAPPING_FAILED,
    LIST_INPUT_MAPPINGS_FAILED,
)
